<div dir="ltr" markdown="1">

```
#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - wget
  - gnupg-agent
  - software-properties-common
  - git
  - jq

runcmd:
  - cd /opt
  - bash -c "export CREATE_EASYSETUP_LINK='true';curl i.hiddify.com/release|bash -s -- --no-gui"

final_message: "The system is finally up, after $UPTIME seconds"
output: { all: "| tee -a /root/cloud-init-output.log" }

# you can see the generated link from the website by using 
# https://yourip.sslip.io/hiddify in one hour, after that,
# it will be disappear.
```
</div>
